# default multipart config
spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      enabled: true
      # if not config the uploadfile is null.....
      location: E:\\converter-output\\tmp
  # redeploy thymeleaf
  thymeleaf:
    cache: false

#default logger config
logging:
  config: classpath:logback.xml
  level:
    root: info

# default server config
server:
  port: 8080
  servlet:
    context-path: /converter-api

# default user converter config
convert:
  # default output-folder
  outputFolder: E:\\converter-output
  video:
    vca:
      default: ffmpeg
      ffmpeg:
        path: D:\\ffmpeg\\bin
        toImage:
          fps: 0.2
  audio:
    # default asr tool
    asr:
      default: baidu
      #baidu asr config
      baidu:
        appId: 10879396
        apiKey: 3l1ZjunSuCLyvhYi91WXQvas
        secretKey: uFVS2XNUvuDlFxPVfpUUA7jxqzw4AMN9
        segmentTime: 60
  image:
    #default ocr tool
    ocr:
      default: youtu
      #tencent youtu ocr tool config
      youtu:
        appId: 10125304
        secretId: AKIDVs45xejwtvmW5SpdkjYGpDUZTIwOp0Hn
        secretKey: a0EHCwgHhgnogMCvUr33uhKl195qSwip
        userId: 1071552744
        time: 600000