# default logger config
logging:
  level:
    root: debug
    springfox.documentation: warn
    org.springframework: warn
    org.hibernate: warn
    org.thymeleaf: warn
    org.apache: warn
    org.quartz: warn
    io.swagger: warn
    org.zbus: warn
    sun.rmi: warn
  file: ./stdout.log

# default server config
server:
  port: 8080
  servlet:
    context-path: /converter-api

# default rocketmq config
apache:
  rocketmq:
    consumer:
      # consumer group
      push-consumer: yogurt-consumer
    producer:
      # producer group
      producer-group: yogurt-producer
    # nameserver address
    namesrvAddr: 192.168.255.130:9876

# default user converter config
convert:
  # whether to clean the temp directory in 1:00am every Sunday
  clean-tmp: true
  # Whether to enable the asynchronous interface
  enable-async: false
  # sync interface config
  sync:
    upload-file-size: 50MB
    output-folder: E:\\converter-output\\
  # async interface config
  async:
    upload-file-size: 500MB
    output-folder: E:\\converter-output\\async\\
  video:
    vca:
      default: ffmpeg
      ffmpeg:
        # in windows os, it's Necessary, in unix os, it will load by system environment
        path: D:\\ffmpeg\\bin\\
        toImage:
          fps: 0.2
  audio:
    # default asr tool
    asr:
      default: baidu
      # baidu is 60s/seg ; shhan is 20s/seg
      seg-duration: 60
      #baidu asr config
      baidu:
        appId: 11067243
        apiKey: iDEvPvY4zT9CzFgYKMQY6eAi
        secretKey: Wkeh8gIbB2LrNBtGwuechG8TUkLlB2TY
      xfyun:
        appId: 5ab9e7d5
        secretKey: fea13a3145f35c56bd602fb2c3a817cc
      shhan:
        base-url: http://172.16.8.103:8177/shRecBase/
  image:
    #default ocr tool
    ocr:
      default: tesseract
      #tencent youtu ocr tool config
      youtu:
        appId: 10125304
        secretId: AKIDVs45xejwtvmW5SpdkjYGpDUZTIwOp0Hn
        secretKey: a0EHCwgHhgnogMCvUr33uhKl195qSwip
        userId: 1071552744
      # abbyy fineReader engine config
      abbyy:
        path: /opt/ABBYY/FREngine11/Bin
        license: SWTT-1101-1006-4491-7660-4166
      # tesseract config
      tesseract:
        # language package path
        datapath: D:\tessdata
