# default logger config
logging:
  level:
    root: WARN
  file:
    max-history: 7
    max-size: 100MB
  path: ./stdout.log

# default server config
server:
  port: 12345
  servlet:
    context-path: /kbase-media

# default user converter config
convert:
  # whether to clean the temp directory in 1:00am every Sunday
  clean-tmp: true
  # Whether to enable the asynchronous interface
  enable-async: false
  # sync interface config
  sync:
    upload-file-size: 500MB
    output-folder: /tmp/convert/
   # async interface config
  async:
    upload-file-size: 500MB
    output-folder: /tmp/convert/async/
  video:
    vca:
      default: ffmpeg
      ffmpeg:
        # ffmpeg bin path
        path: /opt/ffmpeg/ffmpeg-3.0/
        toImage:
          fps: 0.2
  audio:
    # default asr tool
    asr:
      default: shhan
      #baidu asr config
      baidu:
        appId: 11067243
        apiKey: iDEvPvY4zT9CzFgYKMQY6eAi
        secretKey: Wkeh8gIbB2LrNBtGwuechG8TUkLlB2TY
      shhan:
        base-url: http://172.16.8.103:8177/shRecBase/
  image:
    #default ocr tool
    ocr:
      default: youtu
      #tencent youtu ocr tool config
      youtu:
        appId: 10125304
        secretId: AKIDVs45xejwtvmW5SpdkjYGpDUZTIwOp0Hn
        secretKey: a0EHCwgHhgnogMCvUr33uhKl195qSwip
        userId: 1071552744
      # abbyy fineReader engine config
      abbyy:
        path: /opt/ABBYY/FREngine11/Bin
        license: SWTT-1101-1006-4491-7660-4166
      # tesseract config
      tesseract:
        # language package path
        datapath: /opt/tesseract/tessdata

# kbase-monitor config
spring:
  application:
    name: kbase-media
  boot:
    admin:
      client:
        url: "http://172.16.8.143:8888"
        username: admin
        password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  server:
    ssl:
      enabled: false